[[language]]
name = "python"
auto-format = true

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "typescript"
scope = "source.ts"
roots = ["package.json", "tsconfig.json"]
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "{file}"] }