# .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # To create releases and upload assets

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Prepare setup script
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          sed -i "s#^VERSION=.*#VERSION=\"${VERSION}\"#" setup.sh

      - name: Determine pre-release status
        id: is_prerelease
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          if [[ "$VERSION" == *-* ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Release Notes
        id: release_notes
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          GITHUB_REPO_URL="https://github.com/${{ github.repository }}"
          SETUP_URL="${GITHUB_REPO_URL}/releases/download/${VERSION}/setup.sh"

          NOTES=$(cat <<EOF
          ## Installation

          To install this version, run the following command:

          \`\`\`sh
          curl -sSL "${SETUP_URL}" | sh
          \`\`\`

          ### Install to a custom directory:

          \`\`\`sh
          curl -sSL "${SETUP_URL}" | sh -s -- ./my-custom-env
          \`\`\`
          EOF
          )
          {
            echo "NOTES<<EOF"
            echo "$NOTES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.release_notes.outputs.NOTES }}
          prerelease: ${{ steps.is_prerelease.outputs.prerelease }}
          files: setup.sh

  build-and-upload:
    name: Build and Upload Assets
    needs: create-release
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-linux-android
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tool
        if: runner.os == 'Linux' && matrix.target != 'x86_64-unknown-linux-gnu'
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build binary
        run: |
          if [[ "${{ runner.os }}" == "macOS" || "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
            cargo build --release --target ${{ matrix.target }}
            BINARY_PATH="target/${{ matrix.target }}/release/isoterm"
          else
            cross build --release --target ${{ matrix.target }}
            BINARY_PATH="target/${{ matrix.target }}/release/isoterm"
          fi

          ARCHIVE_NAME="isoterm-${{ matrix.target }}.tar.gz"
          tar -czf "$ARCHIVE_NAME" -C "$(dirname "$BINARY_PATH")" "$(basename "$BINARY_PATH")"
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.create-release.outputs.version }} ${{ env.ARCHIVE_NAME }}
